
version: '3.9'

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_project
    ports: 
      - 5432:5432

volumes:
  postgres_data:
